{% set name = "dargparser" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dargparser-{{ version }}.tar.gz
  sha256: a177d1cf14f3fc93f573dbacdd55e4ebbfa24f7a5f4c4bb4ddd3a37bfe43a1da

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - dargparser = dargparser.version:entry_point

requirements:
  host:
    - python >=3.7
    - setuptools >=45
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.7

test:
  imports:
    - dargparser
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/konstantinjdobler/dargparser
  summary: A lean and hackable typed argument parser for Python.
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/konstantinjdobler/dargparser

extra:
  recipe-maintainers:
    - konstantinjdobler
