{% set name = "dargparser" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dargparser-{{ version }}.tar.gz
  sha256: 50dffb1e12ea7b4d5e0da5930a3d430d6d51bf96a19b0dd6a23ff99402f4a1a4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  entry_points:
    - dargparser = dargparser.version:entry_point

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=45
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - dargparser
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/konstantinjdobler/dargparser
  summary: A lean and hackable typed argument parser for Python.
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/konstantinjdobler/dargparser

extra:
  recipe-maintainers:
    - konstantinjdobler
